name: pm936
on:
  schedule:
    - cron: '31 4 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: pm936
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: pm936
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/pm936/httpcatcher.git"
          source_branch: "main"
          destination_branch: "httpcatcher"
          github_token: ${{ secrets.PAT }}
